#!/bin/bash

# 전체 경로로 myc-chaind 사용하는 버전
CHAIND="$HOME/go/bin/myc-chaind"
CHAIN_ID="mycchain"
NODE="http://localhost:26657"

echo "=== 가맹점 생성 예시 ==="
echo ""
echo "# 1. 스타벅스 가맹점 등록"
echo "$CHAIND tx payment create-merchant starbucks active 1697500000 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 2. 이디야 가맹점 등록"
echo "$CHAIND tx payment create-merchant ediya active 1697500100 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 3. 투썸플레이스 가맹점 등록"
echo "$CHAIND tx payment create-merchant twosome pending 1697500200 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""

echo "=== 결제 트랜잭션 생성 예시 ==="
echo ""
echo "# 1. 스타벅스에서 5000원 결제 (고객: customer001)"
echo "$CHAIND tx payment create-payment starbucks customer001 5000stake completed 1697600000 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 2. 스타벅스에서 12000원 결제 (고객: customer002)"
echo "$CHAIND tx payment create-payment starbucks customer002 12000stake completed 1697600100 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 3. 이디야에서 3500원 결제 (고객: customer001)"
echo "$CHAIND tx payment create-payment ediya customer001 3500stake completed 1697600200 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 4. 이디야에서 4200원 결제 (고객: customer003)"
echo "$CHAIND tx payment create-payment ediya customer003 4200stake pending 1697600300 --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 5. 투썸플레이스에서 8500원 결제 (고객: customer002)"
echo "$CHAIND tx payment create-payment twosome customer002 8500stake completed 1697600400 --from bob --chain-id $CHAIN_ID --node $NODE -y"
echo ""

echo "=== 정산 생성 예시 ==="
echo ""
echo "# 1. 스타벅스 일일 정산 (총 17000원)"
echo "$CHAIND tx payment create-settlement starbucks 17000stake 1697702400 completed --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 2. 이디야 일일 정산 (총 7700원)"
echo "$CHAIND tx payment create-settlement ediya 7700stake 1697702400 pending --from alice --chain-id $CHAIN_ID --node $NODE -y"
echo ""
echo "# 3. 투썸플레이스 일일 정산 (총 8500원)"
echo "$CHAIND tx payment create-settlement twosome 8500stake 1697702400 processing --from bob --chain-id $CHAIN_ID --node $NODE -y"
echo ""

echo "=== 조회 명령어 예시 ==="
echo ""
echo "# 모든 가맹점 조회"
echo "$CHAIND query payment list-merchant --node $NODE"
echo ""
echo "# 특정 가맹점 조회"
echo "$CHAIND query payment show-merchant starbucks --node $NODE"
echo ""
echo "# 모든 결제 내역 조회"
echo "$CHAIND query payment list-payment --node $NODE"
echo ""
echo "# 특정 결제 조회 (ID로)"
echo "$CHAIND query payment show-payment 0 --node $NODE"
echo ""
echo "# 모든 정산 내역 조회"
echo "$CHAIND query payment list-settlement --node $NODE"
echo ""
echo "# 특정 정산 조회 (ID로)"
echo "$CHAIND query payment show-settlement 0 --node $NODE"
echo ""
